# Generated by Django 4.2.3 on 2023-08-23 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_venue_venu_image_alter_venue_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venue',
            old_name='venu_image',
            new_name='venue_image',
        ),
    ]
